language:
- minimal
sudo:
- false
dist:
- trusty
addons:
  apt:
    packages:
    - python3-pip
env:
  global:
  - secure: Pe9O8G8X1gjWmT20hw339Be7CnH6snJHgZOI0RX1H4R95NVEoaDiRoFTfMsKEJvNl0id7zaH3g7dOlaO4cuvjORTATRWgJrGPnHAp9LLiWrrBPP7C0SxqpgoPq61xjR7rveLgdPhMkpt6+g3aGthCHSEMY/aoVXxJUxnrVgG12j5Kt2Ui5vr6Acp+iaWyeC7CMmETq/BdlKxpD2sO60b09BIqb6Y7xSuZv55Q0FBL120P/rNE9MCiyd/A2E4vEYX7hMPFlCCF4GjO0ecuNVKNDoM93d0Lfr7J6k/KPtcR/Qi4wWX6RKwX+hiVkjy7Ghfej+W0I7D9D4MynUi1Io+LerjKr3pKYuDOjhhnm5yeuo+DJJshv/rUJ0Mva3ihADAgiaMT1G8TGpoLXSMSrVNJcRHqq6mNnJ1tcp0aCjlThpDlpZLhJocSAC7GceGHWWuKNbnrEK0vL/8/gal/iuAHnQUnkmlvYCDaxFIfZ/b5/UXqDIDxDJrXp4VDE/ilDqMw86ZdcG6ge8qgGVjLcapHAEoKVT9ZFmB9isdxhXZsHxpFz4D6fvz3n1yAsFWw2e8FTCJBTFbvdbWhteYd2UuFIMr1ECWXXCYB86GBxYQtOqq4GalR16H5VZ0Tku55ZL4LDeHCu5Uo8uBtOzCeoajgnQr/R36jDVKtVM7qeWZFIM=
matrix:
  include:
  - os: linux
    env: TYPE=Debug
  - os: linux
    env: TYPE=Release
script:
- cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DCMAKE_BUILD_TYPE=${TYPE} -DHUNTER_CONFIGURATION_TYPES=${TYPE}
- cmake --build _builds
branches:
  except:
  - "/^pr\\..*/"
